-- Table Membre
CREATE TABLE MEMBRE (
	MEMBRE_ID SERIAL PRIMARY KEY NOT NULL,
	NOM VARCHAR(50),
	PRENOM VARCHAR(50),
	EMAIL VARCHAR(255) UNIQUE NOT NULL,
	PASSWORD VARCHAR(255),
	VERIF BOOL NOT NULL DEFAULT FALSE,
	ADMIN BOOL NOT NULL DEFAULT FALSE
)


-- Valeurs de test

INSERT INTO
	MEMBRE (NOM, PRENOM, EMAIL, PASSWORD, ADMIN, VERIF)
VALUES
	(
		'ZUNDEL',
		'Pierre',
		'pierre.zundel@gmail.com',
		'default',
		TRUE,
		TRUE
	);